// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:nami/ignore_deprecated_utilities/hive/ausbildung.dart';
import 'package:nami/ignore_deprecated_utilities/hive/custom_group.dart';
import 'package:nami/ignore_deprecated_utilities/hive/data_changes.dart';
import 'package:nami/ignore_deprecated_utilities/hive/mitglied.dart';
import 'package:nami/ignore_deprecated_utilities/hive/taetigkeit.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AusbildungAdapter());
    registerAdapter(CustomGroupAdapter());
    registerAdapter(DataChangeAdapter());
    registerAdapter(MitgliedAdapter());
    registerAdapter(TaetigkeitAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AusbildungAdapter());
    registerAdapter(CustomGroupAdapter());
    registerAdapter(DataChangeAdapter());
    registerAdapter(MitgliedAdapter());
    registerAdapter(TaetigkeitAdapter());
  }
}
