name: Deploy App to Androud
'on':
  workflow_dispatch: null
jobs:
  build:
    name: Job 1 - Build Signed AAB
    runs-on: ubuntu-latest
    steps:
      # Step 1 - checkout the repository, making it available to the workflow:
      - uses: actions/checkout@v3
       # Set up Flutter.
      - uses: subosito/flutter-action@v1
        with:
            channel: "stable"
      - name: Checkout flutter_app code
        uses: actions/checkout@v3
      - run: flutter pub get
      - name: Build APK
        run: flutter build apk --split-per-abi --release
      - name: Build APP BUNDLE
        run: flutter build appbundle
      - name: Sign AAb
        id: sign
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: '${{ secrets.ANDROID_KEYSTORE }}'
          alias: '${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}'
          keyStorePassword: '${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}'
          keyPassword: '${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}'
      # Step 9 - Save AAB after Build job is complete to publish it as a Github release in the next job
      - name: Upload app bundle as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
      # Step 10 - Print out the Job Status
      - run: 'echo Build status report=${{ job.status }}'
  deploy:
    name: Job_2 - Deploy aab to playstore
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1 -  Download app bundle
      - name: Download app bundle from artifact
        uses: actions/download-artifact@v2
        with:
          name: app-bundle
      # Step 2- Upload the AAB to play console
      - name: Publish to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: '${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}'
          packageName: com.uxstate.countriespad
          releaseFiles: '${{ github.workspace }}/app-release.aab'
          track: production