name: Test & Build

on:
  workflow_dispatch:

jobs:
  test:
    name: flutter test
    runs-on: ubuntu-latest

    env:
      JAVA_VERSION: '17.0.1'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'
      - run: dart --version

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: dart analyze

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      #- name: Run tests
      #  run: dart test

  version:
    name: flutter version
    runs-on: ubuntu-latest
    outputs:
      releaseversion: ${{ steps.v.outputs.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }} # checkout the correct branch name
          fetch-depth: 0 # fetch the whole repo history
      - name: Git Version
        id: gitversion
        uses: codacy/git-version@2.2.0
        with:
          dev-branch: develop
          prefix: v
      - name: Save git-version
        id: v
        run: echo "::set-output name=version::${{ steps.gitversion.outputs.VERSION }}"

  build:
    needs: [test, version]
    name: flutter build
    runs-on: macos-latest
    env:
      JAVA_VERSION: '11'
      FLUTTER_VERSION: '3.0.0'
    steps:
      - run: echo ${{needs.version.outputs.releaseversion}}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
        #Built /Users/runner/work/dpsg-nami-app/dpsg-nami-app/build/ios/iphoneos/Runner.app.
      - run: flutter build apk --debug #Built build/app/outputs/flutter-apk/app-debug.apk.
      - run: flutter build appbundle
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'build/app/outputs/flutter-apk/*.apk,build/app/outputs/bundle/release/app-release.aab,build/ios/iphoneos/Runner.app'
          token: ${{ secrets.TOKEN }}
          tag: ${{needs.version.outputs.releaseversion}}
          commit: ${{ github.sha }}
